grpc:
  service2:
    host: 0.0.0.0
    port: 50056
  service3:
    host: 0.0.0.0
    port: 50053
  service4:
    host: 0.0.0.0
    port: 50055

redis:
  host: localhost
  port: 6379
  db: 0

logging:
  file: app.log
  level: INFO

output:
  dir: ./output/
